server:
  port: 9000
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false
      username: root
      password: 123456433
  jpa:
    database: MYSQL
    show-sql: false